# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 245b6cdc5d3cef18114d46f75b61c3173051f27e274302e3f9826545dd913574903182a7c553c4c8303e5d6bf565332f94ef4ab9ee0c81f7a2ceff48fe744492

test:
  secret_key_base: 080202e832be6a09153dda1d529b424353d49198d483af5834afe69f2235cd4d139aef7984d4b4b71c2c0f12c03ed9c4ac36be926d6cca49e110b53125b3d0e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
